
x-default-environment: &default-environment
  REDIS_URL: redis://redis:6379
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: postgres
  API_KEY: APIKEY

x-service-urls: &service-urls
  AUTH_URL:  http://digilink-auth:1337
  BACKEND_URL:   http://digilink-backend:3001
  FRONTEND_URL:   http://digilink-frontend:8080

x-auth-env: &auth-env
  <<: *service-urls
  NODE_ENV: production
  DATABASE_HOST: postgres
  DATABASE_PORT: 5432
  DATABASE_USERNAME: postgres
  DATABASE_PASSWORD: postgres
  DATABASE_NAME: digilink-auth
  JWT_SECRET: your-super-secret-key-32-characters-long
  CRYPTO_IV: 09f3739f212ad10ec0a55ea6d5aa0d69
  CRYPTO_KEY: fd54d610bdfa832c57528166b7af44adc292ebe531d922e4ff949295a3929799
  JWT_SECRET_AUTH: 5c39c16b152f4696a11fc3967a2c807c

x-backend-env: &backend-env
  <<: *service-urls
  DATABASE_HOST: postgres
  DATABASE_USERNAME: postgres
  DATABASE_PASSWORD: postgres
  DATABASE_NAME: postgres
  DATABASE_PORT: 5432
  LOOKUP_CRYPTO_IV: 35c80b0d03189ab04c1d68f3385fea4b
  LOOKUP_CRYPTO_KEY: a5fb0a3be3e1b18596ccd372a583347c8323d72a6cf3868efaa17f3370f2201a
  ACCESS_TOKEN_SECRET_WS: 8ffcd8e2d630271e6791def5dd6b37fea39180d69e6002b1d1f154a5
  SESSION_SECRET: 76ca842bd9bbc07826bbecffcdca86f0d26ca22c644361f9f63be3cbf0573005
  CRYPTO_IV: 09f3739f212ad10ec0a55ea6d5aa0d69
  CRYPTO_KEY: fd54d610bdfa832c57528166b7af44adc292ebe531d922e4ff949295a3929799
  CONTROLLER_CRYPTO_IV: b07a8452f29f0f9b5171732426546adb
  CONTROLLER_CRYPTO_KEY: 2ebc6b0d65fca5d954b49b60ffcd77d7ca4bec550a941ba77f98af18c59a7027
  EU_HOSTED_SERVER: false
  SUPPORT_HELP_EMAIL: leonnardo.nascimento@digilock.com
  ACCESS_TOKEN_SECRET: 55f30583ed58487c0c3a71c0fa6c75ff455d297aecd7b2123158e003256c7d904c9cdece2aeac82b3936806c42bfd3a5ba039fb05fc0330a72247b1b6da30130
  REFRESH_TOKEN_SECRET: eb33871b547e9251d255079dfa6ad2f715c7cff5a9c5d682e238b546a6a21c0e30c4cf742278d6ccbdf2b37de263ecc3b88cd3a4e4915db5123d7ecc3fb693e9
  SECRET_KEY: mySuperSecretKey
  NODE_ENV: on-prem
  JWT_SECRET_AUTH: 5c39c16b152f4696a11fc3967a2c807c

services:
  postgres:
    image: postgres:17
    container_name: DigiLink-Postgres
    environment:
      <<: *default-environment
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis:7
    container_name: DigiLink-Redis
    environment:
      <<: *default-environment
    ports:
      - 6379:6379
    volumes:
      - ./redis:/data
    restart: always

  digilink-auth:
    image: auth:v0.0.3
    container_name: DigiLink-Auth
    ports:
      - "1337:1337"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/config-fe.json:/app/config/config-fe.json
      - ./config/config.json:/app/config/config.json
    depends_on:
      - postgres
      - redis
    restart: always
    extra_hosts:
      - "digilink.lan:192.168.50.1"
      - "config.lan:192.168.50.1"
      - "backend.lan:192.168.50.1"
    environment:
      <<: *auth-env

  digilink-backend:
    image: backend:v0.0.3
    container_name: DigiLink-Backend
    ports:
      - "3001:3001"
    depends_on:
      - postgres
      - redis
    volumes:
      - ./config/config-fe.json:/app/config/config-fe.json
      - ./config/config.json:/app/config/config.json
    restart: always
    extra_hosts:
      - "digilink.lan:192.168.50.1"
      - "config.lan:192.168.50.1"
      - "backend.lan:192.168.50.1"
    environment:
      <<: *backend-env

  digilink-frontend:
    image: frontend:v0.0.3
    container_name: DigiLink-Frontend
    ports:
      - "8080:8080"
    volumes:
      - ./config/config-fe.json:/usr/share/nginx/html/config.json:ro
    depends_on:
      - digilink-backend
    restart: always
    extra_hosts:
      - "digilink.lan:192.168.50.1"
      - "config.lan:192.168.50.1"
      - "backend.lan:192.168.50.1"

  nginx:
    image: nginx:1.28
    container_name: DigiLink-Nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - digilink-frontend
      - digilink-backend
      - digilink-auth
    restart: always

volumes:
  postgres_data:
